
# ######### API CONFIGURATIONS ######### #

# ######### CRYPTOCOMPARE API KEY ###### #
CCAPI_KEY = 'CRYPTOCOMPARE_API_KEY_HERE'

# ######### TWITTER ######### #
CONSUMER_SECRET = 'TWITTER_CONSUMER_SECRET_HERE'
CONSUMER_KEY = 'TWITTER_CONSUMER_KEY_HERE'

ACCESS_TOKEN = 'TWITTER_ACCESS_TOKEN_HERE'
ACCESS_TOKEN_SECRET = 'TWITTER_ACCESS_TOKEN_SECRET_HERE'
